name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Extension
        run: |
          zip -r extension.zip . -x "*.git*" -x ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip
          generate_release_notes: true